📓 Lesson 10 — Handling Missing Data
------------------------------------

In [1]:
import numpy as np
import pandas as pd

df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha"],
    "Age":[21,np.nan,23,24],
    "Salary":[40000,45000,np.nan,"IT"]
})
print(df)

    Name   Age Salary
0   Amit  21.0  40000
1  Priya   NaN  45000
2  Rahul  23.0    NaN
3   Neha  24.0     IT

Detect Missing Values — isna()
-------------------------------
df.isna()

This returns True where a value is missing and False where it isn't.

In [2]:
df.isna()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False

Count Missing Values
--------------------

In [3]:
df.isna().sum()

Name      0
Age       1
Salary    1
dtype: int64

isnull()
isna() == isnull():Both detect missing values.

Find Rows With Missing Values
----------------------------

In [5]:
df[df["Age"].isna()]

    Name  Age Salary
1  Priya  NaN  45000

In [6]:
df[df["Salary"].isna()]

    Name   Age Salary
2  Rahul  23.0    NaN

notna() — Find Non-Missing Values
---------------------------------
notna() is the opposite of isna()

isna()   → Is it missing?

notna()  → Is it NOT missing?

In [7]:
df[df["Age"].notna()]

    Name   Age Salary
0   Amit  21.0  40000
2  Rahul  23.0    NaN
3   Neha  24.0     IT

📝 Practice
-------------

In [9]:
df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha"],
    "Age": [21, np.nan, 23, 24],
    "Salary": [40000, 45000, np.nan, 38000],
    "Department": ["IT", "HR", np.nan, "IT"]
})

In [17]:
print(df.isna().sum())
print("_____________________________________")
print(df[df["Salary"].isna()])
print("_____________________________________")
print(df[df["Department"].isna()])

Name          0
Age           1
Salary        1
Department    1
dtype: int64
_____________________________________
    Name   Age  Salary Department
2  Rahul  23.0     NaN        NaN
_____________________________________
    Name   Age  Salary Department
2  Rahul  23.0     NaN        NaN

dropna()
--------
dropna() is used when you want to remove rows or columns containing missing values.

By default, Pandas removes any row that contains at least one missing value

In [20]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha"],
    "Age": [21, np.nan, 23, 24],
    "Salary": [40000, 45000, np.nan, 38000],
    "Department": ["IT", "HR", np.nan, "IT"]
})

print(df)

    Name   Age   Salary Department
0   Amit  21.0  40000.0         IT
1  Priya   NaN  45000.0         HR
2  Rahul  23.0      NaN        NaN
3   Neha  24.0  38000.0         IT

In [19]:
df.dropna()

   Name   Age   Salary Department
0  Amit  21.0  40000.0         IT
3  Neha  24.0  38000.0         IT

axis tells Pandas whether to remove rows or columns

how controls when a row/column should be removed.


| Code                           | Meaning                               |
| ------------------------------ | ------------------------------------- |
| `df.dropna()`                  | Remove rows containing missing values |
| `df.dropna(axis=0)`            | Remove rows                           |
| `df.dropna(axis=1)`            | Remove columns                        |
| `df.dropna(how="any")`         | Remove if any value is missing        |
| `df.dropna(how="all")`         | Remove only if all values are missing |
| `df.dropna(subset=["Salary"])` | Remove rows where Salary is missing   |

In [24]:
print(df.dropna(how="any"))
print("-----------------------------")
print(df.dropna(subset="Salary"))

   Name   Age   Salary Department
0  Amit  21.0  40000.0         IT
3  Neha  24.0  38000.0         IT
-----------------------------
    Name   Age   Salary Department
0   Amit  21.0  40000.0         IT
1  Priya   NaN  45000.0         HR
3   Neha  24.0  38000.0         IT

fillna()
---------

In [46]:
import pandas as pd
import numpy as np
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha"],
    "Age":[21,np.nan,23,24],
    "Salary":[40000,45000,np.nan,38000]
})
#df["Age"]=df["Age"].fillna(25)
print(df)

    Name   Age   Salary
0   Amit  21.0  40000.0
1  Priya   NaN  45000.0
2  Rahul  23.0      NaN
3   Neha  24.0  38000.0

Fill missing values in the whole DataFrame
------------------------------------------

| Data                           | Common filling method |
| ------------------------------ | --------------------- |
| Numerical, relatively balanced | Mean                  |
| Numerical, outliers/skewed     | Median                |
| Categorical                    | Mode                  |

In [42]:
df=df.fillna(0)
print(df)

    Name   Age   Salary
0   Amit  21.0  40000.0
1  Priya   0.0  45000.0
2  Rahul  23.0      0.0
3   Neha  24.0  38000.0

In [47]:
df["Salary"].median()
df["Salary"]=df["Salary"].fillna(df["Salary"].median())
print(df)

    Name   Age   Salary
0   Amit  21.0  40000.0
1  Priya   NaN  45000.0
2  Rahul  23.0  40000.0
3   Neha  24.0  38000.0

In [51]:
df["Age"].mean()
df["Age"]=df["Age"].fillna(df["Age"].mean())
print(df)

    Name        Age   Salary
0   Amit  21.000000  40000.0
1  Priya  22.666667  45000.0
2  Rahul  23.000000  40000.0
3   Neha  24.000000  38000.0

In [53]:
df["Age"]=df["Age"].astype(int)
df["Salary"]=df["Salary"].astype(int)
print(df.dtypes)

Name      object
Age        int32
Salary     int32
dtype: object

📝 Practice
------------

In [64]:
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha","Riya"],
    "Age":[21,np.nan,23,24,np.nan],
    "Salary":[40000,45000,np.nan,38000,50000],
    "Department":["IT","HR",np.nan,"IT","IT"]
})
print(df["Age"].fillna(25))
df["Salary"]=df["Salary"].fillna(df["Salary"].median())
df["Department"]=df["Department"].fillna(df["Department"].mode()[0])
print(df)

0    21.0
1    25.0
2    23.0
3    24.0
4    25.0
Name: Age, dtype: float64
    Name   Age   Salary Department
0   Amit  21.0  40000.0         IT
1  Priya   NaN  45000.0         HR
2  Rahul  23.0  42500.0         IT
3   Neha  24.0  38000.0         IT
4   Riya   NaN  50000.0         IT

Lesson 11 — Removing Duplicates
-------------------------------
A duplicate row is a row that appears more than once in your DataFrame.

In [77]:
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Amit"],
    "Age":[21,22,23,21],
    "Salary":[40000,45000,50000,40000]
})
df.duplicated()
df.duplicated().sum()
print(df)

    Name  Age  Salary
0   Amit   21   40000
1  Priya   22   45000
2  Rahul   23   50000
3   Amit   21   40000

In [71]:
df=df.drop_duplicates()
print(df)

    Name  Age  Salary
0   Amit   21   40000
1  Priya   22   45000
2  Rahul   23   50000

📝 Practice
-------------

In [82]:
df = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 101, 104, 102],
    "Name": ["Amit", "Priya", "Rahul", "Amit", "Neha", "Priya"],
    "Salary": [40000, 45000, 50000, 40000, 38000, 45000]
})
print("Find which rows are duplicates")
print(df.duplicated())
print("Count the number of duplicate rows:",df.duplicated().sum())
df.drop_duplicates()
df.duplicated(subset=["Employee_ID"])

Find which rows are duplicates
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
Count the number of duplicate rows: 2

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

duplicated() is used to identify duplicate rows and returns a Boolean Series, while drop_duplicates() removes duplicate rows from the DataFrame
| Topic                     | What to remember                                      | Syntax / Example                                      |
| ------------------------- | ----------------------------------------------------- | ----------------------------------------------------- |
| **Missing data**          | Missing values are commonly represented as `NaN`      | `np.nan`                                              |
| **Detect missing values** | `isna()` returns `True` for missing values            | `df.isna()`                                           |
| **Count missing values**  | Count missing values in each column                   | `df.isna().sum()`                                     |
| **`isnull()`**            | Same functionality as `isna()`                        | `df.isnull()`                                         |
| **Find missing rows**     | Filter rows where a column is missing                 | `df[df["Age"].isna()]`                                |
| **Find non-missing rows** | Use `notna()`                                         | `df[df["Age"].notna()]`                               |
| **`dropna()`**            | Removes rows/columns containing missing values        | `df.dropna()`                                         |
| **Remove rows**           | `axis=0` means rows                                   | `df.dropna(axis=0)`                                   |
| **Remove columns**        | `axis=1` means columns                                | `df.dropna(axis=1)`                                   |
| **`how="any"`**           | Remove if **at least one** value is missing           | `df.dropna(how="any")`                                |
| **`how="all"`**           | Remove only if **all** values are missing             | `df.dropna(how="all")`                                |
| **`subset`**              | Check missing values only in specific column(s)       | `df.dropna(subset=["Salary"])`                        |
| **`fillna()`**            | Replaces missing values instead of deleting rows      | `df["Age"].fillna(25)`                                |
| **Fill with fixed value** | Replace missing values with a chosen value            | `df["Age"] = df["Age"].fillna(25)`                    |
| **Fill with mean**        | Useful for numerical data when appropriate            | `df["Age"].fillna(df["Age"].mean())`                  |
| **Fill with median**      | Useful when data has outliers/skew                    | `df["Salary"].fillna(df["Salary"].median())`          |
| **Fill with mode**        | Common for categorical data                           | `df["Department"].fillna(df["Department"].mode()[0])` |
| **Mean vs median**        | Mean is affected by outliers; median is less affected | Salary → often median                                 |
| **Outlier**               | An unusually extreme value                            | `500000` among salaries around `30–40k`               |
| **Skewed data**           | Distribution is uneven / has a long tail              | High-salary values can create right skew              |

Lesson 12 — Data Cleaning: replace() & str.strip()
--------------------------------------------------
| Method      | Purpose                              |
| ----------- | ------------------------------------ |
| `replace()` | Replace **specific existing values** |
| `fillna()`  | Replace **missing (`NaN`) values**   |

📝 Practice
----------

In [84]:
df = pd.DataFrame({
    "Name": [" Amit ", "PRIYA", " Rahul ", "Neha", " Riya "],
    "Department": ["IT", " it", "HR ", "Human Resources", " IT "],
    "Status": ["active", "ACTIVE", "inactive", "Active", " active "]
})
print(df)

      Name       Department    Status
0    Amit                IT    active
1    PRIYA               it    ACTIVE
2   Rahul               HR   inactive
3     Neha  Human Resources    Active
4    Riya               IT    active

In [100]:
print(df["Name"].str.strip())
print("_______________________")
print(df["Name"].str.strip().str.title())
df["Department"]=df["Department"].str.strip().str.upper()
print("-----------------------------")
print(df["Department"])
df["Department"]=df["Department"].replace("HUMAN RESOURCES","HR")
print(df["Department"])
df["Status"]=df["Status"].str.upper().str.strip()
print(df)

0     Amit
1    PRIYA
2    Rahul
3     Neha
4     Riya
Name: Name, dtype: object
_______________________
0     Amit
1    Priya
2    Rahul
3     Neha
4     Riya
Name: Name, dtype: object
-----------------------------
0    IT
1    IT
2    HR
3    HR
4    IT
Name: Department, dtype: object
0    IT
1    IT
2    HR
3    HR
4    IT
Name: Department, dtype: object
    Name Department    Status
0   Amit         IT    ACTIVE
1  PRIYA         IT    ACTIVE
2  Rahul         HR  INACTIVE
3   Neha         HR    ACTIVE
4   Riya         IT    ACTIVE

Lesson 13 — String Operations in Pandas
---------------------------------------

| Method             | Checks          |
| ------------------ | --------------- |
| `str.contains()`   | Anywhere inside |
| `str.startswith()` | Beginning       |
| `str.endswith()`   | End             |

📝 Practice
-------------

In [109]:
df = pd.DataFrame({
    "Name": ["Amit Kumar", "Priya Singh", "Rahul Kumar", "Neha Sharma", "Amit Singh"],
    "Department": ["IT", "HR", "IT", "Finance", "IT"]
})

In [115]:
print(df["Name"].str.contains("Kumar"))
print(df["Name"].str.startswith("A"))
print("----------------------------")
print(df["Name"].str.endswith("Singh"))
print(df["Name"].replace("Kumar","Sharma"))
print(df["Name"].str.contains("Amit",case=False))

0     True
1    False
2     True
3    False
4    False
Name: Name, dtype: bool
0     True
1    False
2    False
3    False
4     True
Name: Name, dtype: bool
----------------------------
0    False
1     True
2    False
3    False
4     True
Name: Name, dtype: bool
0     Amit Kumar
1    Priya Singh
2    Rahul Kumar
3    Neha Sharma
4     Amit Singh
Name: Name, dtype: object
0     True
1    False
2    False
3    False
4     True
Name: Name, dtype: bool

Lesson 14 — Sorting Data in Pandas
----------------------------------
sort_values() → sort based on column values

sort_index() → sort based on row/column index

In [121]:
import pandas as pd
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha","Riya"],
    "Age":[24,21,27,23,25],
    "Salary":[50000,45000,70000,38000,60000]
})
df.sort_values("Salary")

    Name  Age  Salary
3   Neha   23   38000
1  Priya   21   45000
0   Amit   24   50000
4   Riya   25   60000
2  Rahul   27   70000

In [117]:
#By default, sorting is ascending.
df.sort_values("Salary",ascending=False)

    Name  Age  Salary
2  Rahul   27   70000
4   Riya   25   60000
0   Amit   24   50000
1  Priya   21   45000
3   Neha   23   38000

Sort by multiple columns
-----------------------

In [119]:
df.sort_values(["Name","Salary"])

    Name  Age  Salary
0   Amit   24   50000
3   Neha   23   38000
1  Priya   21   45000
2  Rahul   27   70000
4   Riya   25   60000

In [124]:
df.sort_values(["Name","Salary"],ascending=[True,False])

    Name  Age  Salary
0   Amit   24   50000
3   Neha   23   38000
1  Priya   21   45000
2  Rahul   27   70000
4   Riya   25   60000

sort_index()
-------------
sort_index() sorts the DataFrame based on its index.

In [126]:
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul"],
    "Salary":[50000,45000,70000]
},index=[3,1,2])
print(df)

    Name  Salary
3   Amit   50000
1  Priya   45000
2  Rahul   70000

In [127]:
df.sort_index()

    Name  Salary
1  Priya   45000
2  Rahul   70000
3   Amit   50000

sort_values() vs sort_index()
------------------------------

| Method          | Sorts by          |
| --------------- | ----------------- |
| `sort_values()` | **Column values** |
| `sort_index()`  | **Index labels**  |

In [147]:
df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha", "Riya"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Age": [24, 21, 27, 23, 25],
    "Salary": [50000, 45000, 70000, 38000, 60000]
})
print(df.sort_values(["Salary"]))
print("________________________")
print(df.sort_values(["Salary"],ascending=False))
print("-------------------------")
print(df.sort_values(["Age"]))
print("--------------------------")
print(df.sort_values(["Department","Salary"],ascending=[True,False]))
df.index = [5, 3, 1, 4, 2]
print(df.sort_index())

    Name Department  Age  Salary
3   Neha    Finance   23   38000
1  Priya         HR   21   45000
0   Amit         IT   24   50000
4   Riya         HR   25   60000
2  Rahul         IT   27   70000
________________________
    Name Department  Age  Salary
2  Rahul         IT   27   70000
4   Riya         HR   25   60000
0   Amit         IT   24   50000
1  Priya         HR   21   45000
3   Neha    Finance   23   38000
-------------------------
    Name Department  Age  Salary
1  Priya         HR   21   45000
3   Neha    Finance   23   38000
0   Amit         IT   24   50000
4   Riya         HR   25   60000
2  Rahul         IT   27   70000
--------------------------
    Name Department  Age  Salary
3   Neha    Finance   23   38000
4   Riya         HR   25   60000
1  Priya         HR   21   45000
2  Rahul         IT   27   70000
0   Amit         IT   24   50000
    Name Department  Age  Salary
1  Rahul         IT   27   70000
2   Riya         HR   25   60000
3  Priya         HR   21   45000
4   Neha    Finance   23   38000
5   Amit         IT   24   50000