Lesson 3 — DataFrame Data Selection
-----------------------------------

In [7]:
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul", "Neha", "Rohan"],
    "Python": [85, 78, 92, 68, 88],
    "SQL": [90, 82, 95, 70, 91],
    "Salary": [40000, 45000, 60000, 35000, 55000]
}

df = pd.DataFrame(data)

In [6]:
print("Selecting One Column")
print(df["Python"])
print("Selecting Multiple Columns")
print(df[["Name","Python","Salary"]])

Selecting One Column
0    85
1    78
2    92
3    68
4    88
Name: Python, dtype: int64
Selecting Multiple Columns
    Name  Python  Salary
0   Amit      85   40000
1  Priya      78   45000
2  Rahul      92   60000
3   Neha      68   35000
4  Rohan      88   55000

In [9]:
print("Selects the row whose index label is 0:")
df.loc[0]

Selects the row whose index label is 0:

Name       Amit
Python       85
SQL          90
Salary    40000
Name: 0, dtype: object

In [10]:
print("Selecting Specific Rows and Columns:")
df.loc[0,"Name"]

Selecting Specific Rows and Columns:

'Amit'

In [13]:
print("Give the first row:")
df.iloc[0]

Give the first row:

Name       Amit
Python       85
SQL          90
Salary    40000
Name: 0, dtype: object

In [12]:
print("First row, second column.")
df.iloc[0,1]

First row, second column.

85

In [15]:
print("Give me the names and salaries of Rahul and Rohan.")
df.loc[[2,4],["Name","Salary"]]

Give me the names and salaries of Rahul and Rohan.

    Name  Salary
2  Rahul   60000
4  Rohan   55000

In [27]:
print(df["Python"])
print("-----------")
print(df[["Name","Salary"]])
print("-----------")
print(df.loc[0])
print("-----------")
print(df.loc[2])
print("-----------")
print(df.loc[[2],["Name","Salary"]])

0    85
1    78
2    92
3    68
4    88
Name: Python, dtype: int64
-----------
    Name  Salary
0   Amit   40000
1  Priya   45000
2  Rahul   60000
3   Neha   35000
4  Rohan   55000
-----------
Name       Amit
Python       85
SQL          90
Salary    40000
Name: 0, dtype: object
-----------
Name      Rahul
Python       92
SQL          95
Salary    60000
Name: 2, dtype: object
-----------
    Name  Salary
2  Rahul   60000

In [28]:
df["Salary"]>50000

0    False
1    False
2     True
3    False
4     True
Name: Salary, dtype: bool

In [29]:
df[df["Salary"]>50000]

    Name  Python  SQL  Salary
2  Rahul      92   95   60000
4  Rohan      88   91   55000

In [32]:
print("Find employees whose Python marks are greater than 80 AND salary is greater than ₹50,000.")
df[(df["Python"]>80)&(df["Salary"]>50000)]

Find employees whose Python marks are greater than 80 AND salary is greater than ₹50,000.

    Name  Python  SQL  Salary
2  Rahul      92   95   60000
4  Rohan      88   91   55000

🧪 Your Practice
-----------------

In [39]:
print("Find employees whose Python marks are greater than 80:")
print(df[df["Python"]>80])
print("-----------------")
print("Find employees whose salary is less than ₹45,000:")
print(df[df["Salary"]<45000])
print("Find employees whose SQL marks are greater than or equal to 90:")
print(df[df["SQL"]>=90])

Find employees whose Python marks are greater than 80:
    Name  Python  SQL  Salary
0   Amit      85   90   40000
2  Rahul      92   95   60000
4  Rohan      88   91   55000
-----------------
Find employees whose salary is less than ₹45,000:
   Name  Python  SQL  Salary
0  Amit      85   90   40000
3  Neha      68   70   35000
Find employees whose SQL marks are greater than or equal to 90:
    Name  Python  SQL  Salary
0   Amit      85   90   40000
2  Rahul      92   95   60000
4  Rohan      88   91   55000

In [44]:
print(df[(df["Python"]>80)&(df["SQL"]>90)])
print("--------------------------------")
print(df[(df["Python"]>90)|(df["Salary"]>50000)])
print("--------------------------------")
print(df[(df["Python"]>=85)&(df["Salary"]>=50000)])

    Name  Python  SQL  Salary
2  Rahul      92   95   60000
4  Rohan      88   91   55000
--------------------------------
    Name  Python  SQL  Salary
2  Rahul      92   95   60000
4  Rohan      88   91   55000
--------------------------------
    Name  Python  SQL  Salary
2  Rahul      92   95   60000
4  Rohan      88   91   55000

🎯 Interview Question
----------------------
Why do we use & instead of and when filtering a Pandas DataFrame?

"& is used in Pandas for element-wise AND operations between Series conditions. The Python and operator expects a single Boolean value, whereas a Pandas condition produces multiple Boolean values—one for each row."

Lesson 4-isin() in Pandas
--------------------------
isin(), which is useful when you want to filter rows matching multiple specific values.

In [48]:
print("--Without isin()---")
df[
    (df["Name"] == "Amit") |
    (df["Name"] == "Rahul") |
    (df["Name"] == "Rohan")
]

--Without isin()---

    Name  Python  SQL  Salary
0   Amit      85   90   40000
2  Rahul      92   95   60000
4  Rohan      88   91   55000

In [47]:

print("--with isin()--")
df[df["Name"].isin(["Amit","Rahul"])]

--with isin()--

    Name  Python  SQL  Salary
0   Amit      85   90   40000
2  Rahul      92   95   60000

In [61]:
print("---Find employees whose names are:(Amit, Rahul, Rohan)Using .isin()--")
print(df[df["Name"].isin(["Amit","Rahul","Rohan"])])
print("____________")
print("---Find employees whose names are:(Priya or Neha)Using .isin()--")
print(df[df["Name"].isin(["Priya"])|df["Name"].isin(["Neha"])])
print("____________")
print(df[~df["Name"].isin(["Amit","Rahul"])])
print("____________")
print(df[df["Python"].isin([78,88,92])])

---Find employees whose names are:(Amit, Rahul, Rohan)Using .isin()--
    Name  Python  SQL  Salary
0   Amit      85   90   40000
2  Rahul      92   95   60000
4  Rohan      88   91   55000
____________
---Find employees whose names are:(Priya or Neha)Using .isin()--
    Name  Python  SQL  Salary
1  Priya      78   82   45000
3   Neha      68   70   35000
____________
    Name  Python  SQL  Salary
1  Priya      78   82   45000
3   Neha      68   70   35000
4  Rohan      88   91   55000
____________
    Name  Python  SQL  Salary
1  Priya      78   82   45000
2  Rahul      92   95   60000
4  Rohan      88   91   55000

Lesson5-between() for Range Filtering
--------------------------------
between() checks whether each value in a Pandas Series falls between a lower limit and upper limit.

== → one exact value
    
.isin() → multiple specific values

between() → values within a range

| Code                                   | Meaning     |
| -------------------------------------- | ----------- |
| `between(40, 50)`                      | 40 ≤ x ≤ 50 |
| `between(40, 50, inclusive="both")`    | 40 ≤ x ≤ 50 |
| `between(40, 50, inclusive="neither")` | 40 < x < 50 |
| `between(40, 50, inclusive="left")`    | 40 ≤ x < 50 |
| `between(40, 50, inclusive="right")`   | 40 < x ≤ 50 |

In [69]:
print("Find employees whose Salary is between ₹40,000 and ₹55,000")
print(df[df["Salary"].between(40000,55000)])
print("-------------------------------------")
print("Find employees whose Python marks are between 80 and 90")
print(df[df["Python"].between(80,90)])
print("-------------------------------------")
print("Find employees whose SQL marks are between 85 and 95")
print(df[df["SQL"].between(85,95)])
print("-------------------------------------")
print("Find employees whose salary is between ₹40,000 and ₹60,000, but exclude both boundaries.")
print(df[df["Salary"].between(40000,60000, inclusive="neither")])

Find employees whose Salary is between ₹40,000 and ₹55,000
    Name  Python  SQL  Salary
0   Amit      85   90   40000
1  Priya      78   82   45000
4  Rohan      88   91   55000
-------------------------------------
Find employees whose Python marks are between 80 and 90
    Name  Python  SQL  Salary
0   Amit      85   90   40000
4  Rohan      88   91   55000
-------------------------------------
Find employees whose SQL marks are between 85 and 95
    Name  Python  SQL  Salary
0   Amit      85   90   40000
2  Rahul      92   95   60000
4  Rohan      88   91   55000
-------------------------------------
Find employees whose salary is between ₹40,000 and ₹60,000, but exclude both boundaries.
    Name  Python  SQL  Salary
1  Priya      78   82   45000
4  Rohan      88   91   55000

Lesson 7 — query() for DataFrame Filtering
------------------------------------------
query() lets you filter a DataFrame using a readable condition written as a string.

| Method            | Example                                 | Best use            |
| ----------------- | --------------------------------------- | ------------------- |
| Boolean filtering | `df[df["Salary"] > 50000]`              | General filtering   |
| `.isin()`         | `df[df["Name"].isin([...])]`            | Specific values     |
| `.between()`      | `df[df["Salary"].between(40000,55000)]` | Range               |
| `query()`         | `df.query("Salary > 50000")`            | Readable conditions |

Practice 
-----------

In [79]:
print("Find employees whose Python marks are greater than 80 using query():")
print(df.query("Python>80"))
print("_______________________________")
print("find employees whose Salary is greater than 50,000 AND SQL marks are greater than 90")
print(df.query("Salary>50000 and SQL>90"))
print("_______________________________")
print("Find employees whose Python marks are greater than 90 OR Salary is greater than 50,000")
print(df.query("Python>90 or Salary>50000"))
print("_______________________________")
print("Find employees whose:Python marks are at least 85 AND salary is at least ₹50,000.Using query() only")
print(df.query("Python>=85 and Salary >=50000"))
print("_______________________________")

Find employees whose Python marks are greater than 80 using query():
    Name  Python  SQL  Salary
0   Amit      85   90   40000
2  Rahul      92   95   60000
4  Rohan      88   91   55000
_______________________________
find employees whose Salary is greater than 50,000 AND SQL marks are greater than 90
    Name  Python  SQL  Salary
2  Rahul      92   95   60000
4  Rohan      88   91   55000
_______________________________
Find employees whose Python marks are greater than 90 OR Salary is greater than 50,000
    Name  Python  SQL  Salary
2  Rahul      92   95   60000
4  Rohan      88   91   55000
_______________________________
Find employees whose:Python marks are at least 85 AND salary is at least ₹50,000.Using query() only
    Name  Python  SQL  Salary
2  Rahul      92   95   60000
4  Rohan      88   91   55000
_______________________________