Lesson 16 — merge(), join() & concat()
-----------------------------------

Employee Information
-------------------

In [8]:
import pandas as pd

employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104],
    "Name": ["Amit", "Priya", "Rahul", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance"]
})

Salary information
------------------

In [9]:
salary = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104],
    "Salary": [50000, 45000, 70000, 38000]
})

In [10]:
result=pd.merge(employees,salary,on="Employee_ID")
print(result)

   Employee_ID   Name Department  Salary
0          101   Amit         IT   50000
1          102  Priya         HR   45000
2          103  Rahul         IT   70000
3          104   Neha    Finance   38000

merge() with different key names
----------------------------------
Sometimes the common columns have different names.

In [5]:
employees=pd.DataFrame({
    "Employee_ID":[101,102,103],
    "Name":["Amit","Priya","Rahul"]
})
salary=pd.DataFrame({
    "ID":[101,102,103],
    "Salary":[50000,45000,70000]
})

In [6]:
pd.merge(employees,salary,left_on="Employee_ID",right_on="ID")

   Employee_ID   Name   ID  Salary
0          101   Amit  101   50000
1          102  Priya  102   45000
2          103  Rahul  103   70000

Types of Merge
--------------
The four important types are:
| Merge   | Meaning                          |
| ------- | -------------------------------- |
| `inner` | Only matching records            |
| `left`  | All records from left DataFrame  |
| `right` | All records from right DataFrame |
| `outer` | All records from both DataFrames |

In [13]:
pd.merge(employees,salary,on="Employee_ID",how="inner")

   Employee_ID   Name Department  Salary
0          101   Amit         IT   50000
1          102  Priya         HR   45000
2          103  Rahul         IT   70000
3          104   Neha    Finance   38000

🎯 Practice 1
------------

In [16]:
result=pd.merge(employees,salary,on="Employee_ID",how="inner")
print(result)
print("_______________________________")
result_1=pd.merge(employees,salary,on="Employee_ID",how="left")
print(result_1)
print("_______________________________")
result_2=pd.merge(employees,salary,on="Employee_ID",how="right")
print(result_2)
print("_______________________________")
result_3=pd.merge(employees,salary,on="Employee_ID",how="outer")
print(result_3)

   Employee_ID   Name Department  Salary
0          101   Amit         IT   50000
1          102  Priya         HR   45000
2          103  Rahul         IT   70000
3          104   Neha    Finance   38000
_______________________________
   Employee_ID   Name Department  Salary
0          101   Amit         IT   50000
1          102  Priya         HR   45000
2          103  Rahul         IT   70000
3          104   Neha    Finance   38000
_______________________________
   Employee_ID   Name Department  Salary
0          101   Amit         IT   50000
1          102  Priya         HR   45000
2          103  Rahul         IT   70000
3          104   Neha    Finance   38000
_______________________________
   Employee_ID   Name Department  Salary
0          101   Amit         IT   50000
1          102  Priya         HR   45000
2          103  Rahul         IT   70000
3          104   Neha    Finance   38000

🎯 Practice 2
--------------

In [17]:
employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104],
    "Name": ["Amit", "Priya", "Rahul", "Neha"]
})

salary = pd.DataFrame({
    "Employee_ID": [101, 102, 105],
    "Salary": [50000, 45000, 60000]
})

In [21]:
result_1=pd.merge(employees,salary,on="Employee_ID",how="inner")
print("------------INNER JOIN--------------")
print(result_1)
result_2=pd.merge(employees,salary,on="Employee_ID",how="left")
print("------------LEFT JOIN----------------")
print(result_2)
result_3=pd.merge(employees,salary,on="Employee_ID",how="right")
print("-------------RIGTH JOIN---------------")
print(result_3)
result_4=pd.merge(employees,salary,on="Employee_ID",how="outer")
print("------------OUTER JOIN_---------------")
print(result_4)

------------INNER JOIN--------------
   Employee_ID   Name  Salary
0          101   Amit   50000
1          102  Priya   45000
------------LEFT JOIN----------------
   Employee_ID   Name   Salary
0          101   Amit  50000.0
1          102  Priya  45000.0
2          103  Rahul      NaN
3          104   Neha      NaN
-------------RIGTH JOIN---------------
   Employee_ID   Name  Salary
0          101   Amit   50000
1          102  Priya   45000
2          105    NaN   60000
------------OUTER JOIN_---------------
   Employee_ID   Name   Salary
0          101   Amit  50000.0
1          102  Priya  45000.0
2          103  Rahul      NaN
3          104   Neha      NaN
4          105    NaN  60000.0

concat()
--------
concat() is used to combine DataFrames by stacking them.

merge() → combine based on a common column/key
concat() → stack DataFrames together

Vertical Concatenation
--------------------

In [24]:
import pandas as pd

jan=pd.DataFrame({
    "Employee_ID":[101,102],
    "Name":["Amit","Priya"],
    "Salary":[50000,45000]
})
feb=pd.DataFrame({
    "Employee_ID":[103,104],
    "Name":["Rahul","Neha"],
    "Salary":[70000,38000]
})
result=pd.concat([jan,feb])
print(result)

   Employee_ID   Name  Salary
0          101   Amit   50000
1          102  Priya   45000
0          103  Rahul   70000
1          104   Neha   38000

ignore_index=True
-----------------
Usually, when stacking datasets, we want a fresh continuous index

In [26]:
result = pd.concat([jan, feb], ignore_index=True)
print(result)

   Employee_ID   Name  Salary
0          101   Amit   50000
1          102  Priya   45000
2          103  Rahul   70000
3          104   Neha   38000

Horizontal Concatenation
-----------------------
concat() can also combine DataFrames side by side.

In [27]:
df1=pd.DataFrame({
    "Name":["Amit","Priya","Rahul"]
})
df2=pd.DataFrame({
    "Salary":[50000,45000,70000]
})
result=pd.concat([df1,df2],axis=1)
print(result)

    Name  Salary
0   Amit   50000
1  Priya   45000
2  Rahul   70000

axis=0 -->rows
axis=1 -->columns

merge()vs concat()
-----------------

| `merge()`                      | `concat()`                   |
| ------------------------------ | ---------------------------- |
| Combines based on key/column   | Stacks/combines DataFrames   |
| Similar to SQL JOIN            | Similar to stacking datasets |
| Uses `on=`                     | Uses `axis=`                 |
| Can use inner/left/right/outer | Can use vertical/horizontal  |

🎯 Practice
------------

In [28]:
df1=pd.DataFrame({
    "Employee_ID":[101,102],
    "Name":["Amit","Priya"]
})
df2=pd.DataFrame({
    "Employee_ID":[103,104],
    "Name":["Rahul","Neha"]
})

In [29]:
result=pd.concat([df1,df2],ignore_index=True)
print(result)

   Employee_ID   Name
0          101   Amit
1          102  Priya
2          103  Rahul
3          104   Neha

In [30]:
result_1=pd.concat([df1,df2],axis=1)
print(result_1)

   Employee_ID   Name  Employee_ID   Name
0          101   Amit          103  Rahul
1          102  Priya          104   Neha

join()
-------
join() combines DataFrames based primarily on their index.

merge() → usually based on columns/keys

join() → usually based on index

In [31]:
df1 = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul"]
}, index=[101, 102, 103])

df2 = pd.DataFrame({
    "Salary": [50000, 45000, 70000]
}, index=[101, 102, 103])

In [32]:
result=df1.join(df2)
print(result)

      Name  Salary
101   Amit   50000
102  Priya   45000
103  Rahul   70000

| `merge()`                            | `join()`                             |
| ------------------------------------ | ------------------------------------ |
| Usually combines using columns/keys  | Usually combines using index         |
| Similar to SQL JOIN                  | Convenient for index-based combining |
| `on="Employee_ID"`                   | Uses index by default                |
| More flexible for key-based matching | Simpler for index-based matching     |

In [33]:
employees = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul"],
    "Department": ["IT", "HR", "IT"]
}, index=[101, 102, 103])

salary = pd.DataFrame({
    "Salary": [50000, 45000, 70000]
}, index=[101, 102, 103])

In [34]:
result=df1.join(df2)
print(result)

      Name  Salary
101   Amit   50000
102  Priya   45000
103  Rahul   70000

merge() vs join() vs concat()
--------------------------
| Function   | Main purpose             | Matching based on |
| ---------- | ------------------------ | ----------------- |
| `merge()`  | Combine related datasets | Column/key        |
| `join()`   | Combine related datasets | Index             |
| `concat()` | Stack/combine DataFrames | Rows or columns   |

🎯 Interview Questions
-----------------------

Q1. When would you use merge() instead of concat()?

Answer:

Use merge() when two DataFrames need to be combined based on a common key/column. Use concat() when DataFrames need to be stacked vertically or horizontally.

Q2. What is the difference between merge() and join()?

merge() generally combines DataFrames using columns or keys, while join() is primarily used to combine DataFrames based on their indexes.

Q3. What does axis=0 and axis=1 mean in concat()?

axis=0 combines DataFrames vertically by rows, while axis=1 combines them horizontally by columns.