Lesson 19 — Datetime & Time Series
-----------------------------------

Datetime--->Dates often come as strings:
pd.to_datetime()

In [3]:
import pandas as pd
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul"],
    "Joining_Date":["2024-01-15","2023-06-20","2025-03-10"]
})
df["Joining_Date"]=pd.to_datetime(df["Joining_Date"])
print(df)
print(df.dtypes)

    Name Joining_Date
0   Amit   2024-01-15
1  Priya   2023-06-20
2  Rahul   2025-03-10
Name                    object
Joining_Date    datetime64[ns]
dtype: object

Extract Year, Month & Day
--------------------------

In [4]:
df["Year"]=df["Joining_Date"].dt.year
print(df)

    Name Joining_Date  Year
0   Amit   2024-01-15  2024
1  Priya   2023-06-20  2023
2  Rahul   2025-03-10  2025

In [6]:
df["Day_Name"] = df["Joining_Date"].dt.day_name()
print(df)

    Name Joining_Date  Year Day_Name
0   Amit   2024-01-15  2024   Monday
1  Priya   2023-06-20  2023  Tuesday
2  Rahul   2025-03-10  2025   Monday

Date Filtering
--------------

In [7]:
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha"],
    "Joining_Date":pd.to_datetime([
        "2022-01-10",
        "2023-05-15",
        "2024-07-20",
        "2025-03-12"
    ])
})

In [8]:
df[df["Joining_Date"]>"2023-01-01"]

    Name Joining_Date
1  Priya   2023-05-15
2  Rahul   2024-07-20
3   Neha   2025-03-12

Sorting by Date
---------------

In [9]:
df=df.sort_values("Joining_Date")
print(df)

    Name Joining_Date
0   Amit   2022-01-10
1  Priya   2023-05-15
2  Rahul   2024-07-20
3   Neha   2025-03-12

In [11]:
df=df.sort_values("Joining_Date",ascending=False)
print(df)

    Name Joining_Date
3   Neha   2025-03-12
2  Rahul   2024-07-20
1  Priya   2023-05-15
0   Amit   2022-01-10

Date Difference
--------------

In [12]:
df = pd.DataFrame({
    "Name": ["Amit", "Priya"],
    "Joining_Date": pd.to_datetime(["2022-01-10", "2024-05-15"])
})

today = pd.Timestamp("2026-09-10")

In [14]:
df["Days_At_Company"]=today-df["Joining_Date"]
print(df)

    Name Joining_Date Days_At_Company
0   Amit   2022-01-10       1704 days
1  Priya   2024-05-15        848 days

In [15]:
df["Days_At_Company"].dt.days

0    1704
1     848
Name: Days_At_Company, dtype: int64

A time series is data recorded over time.

Datetime as an Index
--------------------

In [18]:
import pandas as pd
df=pd.DataFrame({
    "Date":pd.to_datetime([
        "2026-01-01",
        "2026-01-02",
        "2026-01-03"
    ]),
    "Sales":[100,120,150]
})
df=df.set_index("Date")
print(df)

            Sales
Date
2026-01-01    100
2026-01-02    120
2026-01-03    150

Select Data by Date
-------------------

In [20]:
df.loc["2026-01-02"]

Sales    120
Name: 2026-01-02 00:00:00, dtype: int64

In [21]:
df.loc["2026-01-01":"2026-01-02"]

            Sales
Date
2026-01-01    100
2026-01-02    120

🧠 Important Interview Points
----------------------------
pd.to_datetime()--->Converts values into Pandas datetime format so that date/time operations can be performed.

.dt--->Provides datetime-specific properties and methods for a Pandas Series.

DatetimeIndex--->A Pandas index specifically designed for date/time values and time-series operations.

🎯 Practice
------------

In [22]:
df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha", "Riya"],
    "Joining_Date": [
        "2022-01-15",
        "2023-06-20",
        "2024-03-10",
        "2025-08-05",
        "2023-12-25"
    ],
    "Salary": [40000, 50000, 60000, 45000, 55000]
})

In [25]:
df["Joining_Date"]=pd.to_datetime(df["Joining_Date"])
print(df)

    Name Joining_Date  Salary
0   Amit   2022-01-15   40000
1  Priya   2023-06-20   50000
2  Rahul   2024-03-10   60000
3   Neha   2025-08-05   45000
4   Riya   2023-12-25   55000

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha", "Riya", "Karan"],
    "Department": ["IT", "HR", "IT", "HR", "IT", "Finance"],
    "Age": [24, 21, 27, 23, 25, 29],
    "Salary": [50000, 40000, 70000, 60000, 55000, 45000]
})

In [15]:
print(df.groupby("Department")["Salary"].mean())
print("-----------------------------------------")
print(df.groupby("Department")["Salary"].agg(["min","max","mean"]))
print("-----------------------------------------")
df["Dept_Avg_Salary"]=df.groupby("Department")["Salary"].transform("mean")
print(df)
print("-----------------------------------------")
df["Salary_After_Tax"]=df["Salary"].apply(lambda x:x*0.90)
print(df)
print("-----------------------------------------")
df["Department_Code"]=df["Department"].map({
    "IT":1,
    "HR":2,
    "Finance":3
})
print(df)

Department
Finance    45000.000000
HR         50000.000000
IT         58333.333333
Name: Salary, dtype: float64
-----------------------------------------
              min    max          mean
Department
Finance     45000  45000  45000.000000
HR          40000  60000  50000.000000
IT          50000  70000  58333.333333
-----------------------------------------
    Name Department  Age  Salary  Dept_Avg_Salary  Salary_After_Tax  \
0   Amit         IT   24   50000     58333.333333           45000.0
1  Priya         HR   21   40000     50000.000000           36000.0
2  Rahul         IT   27   70000     58333.333333           63000.0
3   Neha         HR   23   60000     50000.000000           54000.0
4   Riya         IT   25   55000     58333.333333           49500.0
5  Karan    Finance   29   45000     45000.000000           40500.0

   Department_Code
0                1
1                2
2                1
3                2
4                1
5                3
-----------------------------------------
    Name Department  Age  Salary  Dept_Avg_Salary  Salary_After_Tax  \
0   Amit         IT   24   50000     58333.333333           45000.0
1  Priya         HR   21   40000     50000.000000           36000.0
2  Rahul         IT   27   70000     58333.333333           63000.0
3   Neha         HR   23   60000     50000.000000           54000.0
4   Riya         IT   25   55000     58333.333333           49500.0
5  Karan    Finance   29   45000     45000.000000           40500.0

   Department_Code
0                1
1                2
2                1
3                2
4                1
5                3
-----------------------------------------
    Name Department  Age  Salary  Dept_Avg_Salary  Salary_After_Tax  \
0   Amit         IT   24   50000     58333.333333           45000.0
1  Priya         HR   21   40000     50000.000000           36000.0
2  Rahul         IT   27   70000     58333.333333           63000.0
3   Neha         HR   23   60000     50000.000000           54000.0
4   Riya         IT   25   55000     58333.333333           49500.0
5  Karan    Finance   29   45000     45000.000000           40500.0

   Department_Code
0                1
1                2
2                1
3                2
4                1
5                3

In [13]:
monthly = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul"],
    "Jan": [50000, 40000, 70000],
    "Feb": [52000, 42000, 72000],
    "Mar": [55000, 45000, 75000]
})
result=monthly.melt(
    id_vars=["Name"],
    var_name="Month",
    value_name="Salary"
)
print(result)

    Name Month  Salary
0   Amit   Jan   50000
1  Priya   Jan   40000
2  Rahul   Jan   70000
3   Amit   Feb   52000
4  Priya   Feb   42000
5  Rahul   Feb   72000
6   Amit   Mar   55000
7  Priya   Mar   45000
8  Rahul   Mar   75000

Practice
--------

In [31]:
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha","Riya"],
    "Joining_Date":[
        "2022-01-15",
        "2023-06-20",
        "2024-03-10",
        "2025-08-05",
        "2023-12-25"
    ],
    "Salary":[40000,50000,60000,45000,55000]
})
print(df)

    Name Joining_Date  Salary
0   Amit   2022-01-15   40000
1  Priya   2023-06-20   50000
2  Rahul   2024-03-10   60000
3   Neha   2025-08-05   45000
4   Riya   2023-12-25   55000

In [33]:
df["Joining_Date"]=pd.to_datetime(df["Joining_Date"])
df["Year"]=df["Joining_Date"].dt.year
df["Month"]=df["Joining_Date"].dt.month
df["Day"]=df["Joining_Date"].dt.day
df["Month_Name"]=df["Joining_Date"].dt.month_name()
print(df)
print("----------------------------------")
print(df[df["Joining_Date"]<"2024-01-01"])
print("----------------------------------")
print(df.sort_values("Joining_Date",ascending=False))
print("----------------------------------")
df=df.set_index("Joining_Date")
print(df)

    Name Joining_Date  Salary  Year  Month  Day Month_Name
0   Amit   2022-01-15   40000  2022      1   15    January
1  Priya   2023-06-20   50000  2023      6   20       June
2  Rahul   2024-03-10   60000  2024      3   10      March
3   Neha   2025-08-05   45000  2025      8    5     August
4   Riya   2023-12-25   55000  2023     12   25   December
----------------------------------
    Name Joining_Date  Salary  Year  Month  Day Month_Name
0   Amit   2022-01-15   40000  2022      1   15    January
1  Priya   2023-06-20   50000  2023      6   20       June
4   Riya   2023-12-25   55000  2023     12   25   December
----------------------------------
    Name Joining_Date  Salary  Year  Month  Day Month_Name
3   Neha   2025-08-05   45000  2025      8    5     August
2  Rahul   2024-03-10   60000  2024      3   10      March
4   Riya   2023-12-25   55000  2023     12   25   December
1  Priya   2023-06-20   50000  2023      6   20       June
0   Amit   2022-01-15   40000  2022      1   15    January
----------------------------------
               Name  Salary  Year  Month  Day Month_Name
Joining_Date
2022-01-15     Amit   40000  2022      1   15    January
2023-06-20    Priya   50000  2023      6   20       June
2024-03-10    Rahul   60000  2024      3   10      March
2025-08-05     Neha   45000  2025      8    5     August
2023-12-25     Riya   55000  2023     12   25   December