Lesson 15 — groupby() & Aggregation
---------------------------------
groupby() is used to divide data into groups and then perform calculations on each group.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha", "Riya"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 45000, 70000, 38000, 60000]
})

print(df)

    Name Department  Salary
0   Amit         IT   50000
1  Priya         HR   45000
2  Rahul         IT   70000
3   Neha    Finance   38000
4   Riya         HR   60000

In [2]:
df.groupby("Department")["Salary"].mean()

Department
Finance    38000.0
HR         52500.0
IT         60000.0
Name: Salary, dtype: float64

In [3]:
df.groupby("Department")["Salary"].sum()

Department
Finance     38000
HR         105000
IT         120000
Name: Salary, dtype: int64

In [4]:
df.groupby("Department")["Name"].count()

Department
Finance    1
HR         2
IT         2
Name: Name, dtype: int64

In [5]:
df.groupby("Department")["Salary"].max()

Department
Finance    38000
HR         60000
IT         70000
Name: Salary, dtype: int64

In [6]:
df.groupby("Department")["Salary"].min()

Department
Finance    38000
HR         45000
IT         50000
Name: Salary, dtype: int64

In [10]:
df.groupby("Department")["Salary"].agg(["mean","max","min"])

               mean    max    min
Department
Finance     38000.0  38000  38000
HR          52500.0  60000  45000
IT          60000.0  70000  50000

Grouping by multiple columns.
------------------------------

In [13]:
import pandas as pd

df = pd.DataFrame({
    "Name": [
        "Amit", "Priya", "Rahul", "Neha", "Riya",
        "Karan", "Sneha", "Vikas", "Pooja", "Arjun"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "IT", "Finance", "HR", "IT", "Finance"
    ],
    "Age": [24, 21, 27, 23, 25, 29, 26, 22, 31, 28],
    "Salary": [
        50000, 45000, 70000, 38000, 60000,
        75000, 48000, 52000, 65000, 55000
    ]
})

In [28]:
print(df.groupby("Department")["Salary"].mean())
print("----------------------------------------")
print(df.groupby("Department")["Salary"].sum())
print("----------------------------------------")
print(df.groupby("Department")["Name"].count())
print("----------------------------------------")
print(df.groupby("Department")["Salary"].max())
print("----------------------------------------")
print(df.groupby("Department")["Salary"].min())
print("----------------------------------------")
print(df.groupby("Department")["Salary"].agg(["mean","max","min"]))
print("----------------------------------------")
print(df.groupby(["Department","Age"])["Salary"].sum())
print("----------------------------------------")
print(df.groupby(["Department","Age"])["Salary"].mean())

Department
Finance    47000.000000
HR         52333.333333
IT         65000.000000
Name: Salary, dtype: float64
----------------------------------------
Department
Finance    141000
HR         157000
IT         260000
Name: Salary, dtype: int64
----------------------------------------
Department
Finance    3
HR         3
IT         4
Name: Name, dtype: int64
----------------------------------------
Department
Finance    55000
HR         60000
IT         75000
Name: Salary, dtype: int64
----------------------------------------
Department
Finance    38000
HR         45000
IT         50000
Name: Salary, dtype: int64
----------------------------------------
                    mean    max    min
Department
Finance     47000.000000  55000  38000
HR          52333.333333  60000  45000
IT          65000.000000  75000  50000
----------------------------------------
Department  Age
Finance     23     38000
            26     48000
            28     55000
HR          21     45000
            22     52000
            25     60000
IT          24     50000
            27     70000
            29     75000
            31     65000
Name: Salary, dtype: int64
----------------------------------------
Department  Age
Finance     23     38000.0
            26     48000.0
            28     55000.0
HR          21     45000.0
            22     52000.0
            25     60000.0
IT          24     50000.0
            27     70000.0
            29     75000.0
            31     65000.0
Name: Salary, dtype: float64

reset_index():
-------------
It converts the DataFrame/Series index back into a normal column and creates a new default index (0, 1, 2, ...).

In [31]:
df.groupby("Department")["Salary"].mean().reset_index()

  Department        Salary
0    Finance  47000.000000
1         HR  52333.333333
2         IT  65000.000000

Lesson 15 — groupby() & Aggregation: agg() with Multiple Columns
----------------------------------------------------------------

In [33]:
df.groupby("Department").agg({
    "Salary":"sum",
    "Age":"mean"
})

            Salary        Age
Department
Finance     141000  25.666667
HR          157000  22.666667
IT          260000  27.750000

In [35]:
df.groupby("Department").agg({
    "Salary":["min","max","mean"],
    "Age":["min","max","mean"]
})

           Salary                      Age
              min    max          mean min max       mean
Department
Finance     38000  55000  47000.000000  23  28  25.666667
HR          45000  60000  52333.333333  21  25  22.666667
IT          50000  75000  65000.000000  24  31  27.750000

groupby() is used to divide the DataFrame into groups based on one or more columns, while agg() is used to apply one or more aggregation functions to those groups.