Lesson 21 — Categorical Data in Pandas
-------------------------------------

In [8]:
import pandas as pd
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha"],
    "Department":["IT","HR","IT","Finance"]
})
print(df.dtypes)
print("------------------------------------------")
df["Department"]=df["Department"].astype("category")
print(df.dtypes)

Name          object
Department    object
dtype: object
------------------------------------------
Name            object
Department    category
dtype: object

In [9]:
df["Department"].cat.categories

Index(['Finance', 'HR', 'IT'], dtype='object')

cat is the categorical accessor, similar to .str for strings and .dt for dates.

In [10]:
df["Department"]=df["Department"].cat.add_categories(["Marketing"])

In [12]:
print(df["Department"])

0         IT
1         HR
2         IT
3    Finance
Name: Department, dtype: category
Categories (4, object): ['Finance', 'HR', 'IT', 'Marketing']

Rename categories
-----------------

In [13]:
df["Department"]=df["Department"].cat.rename_categories({
    "IT":"Information Technology",
    "HR":"Human Resources",
    "Finance":"Finance"
})

Ordered categories
------------------

In [14]:
df["Priority"]=pd.Categorical(
    ["Low","High","Medium","Low"],
    categories=["Low","Medium","High"],
    ordered=True
)
df.sort_values("Priority")

    Name              Department Priority
0   Amit  Information Technology      Low
3   Neha                 Finance      Low
2  Rahul  Information Technology   Medium
1  Priya         Human Resources     High

In [23]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha", "Riya", "Karan"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Status": ["Active", "Active", "Inactive", "Active", "Inactive", "Active"],
    "Performance": ["High", "Medium", "Low", "High", "Medium", "High"]
})
print(df.dtypes)

Name           object
Department     object
Status         object
Performance    object
dtype: object

In [24]:
df["Department"]=df["Department"].astype("category")
print(df)

    Name Department    Status Performance
0   Amit         IT    Active        High
1  Priya         HR    Active      Medium
2  Rahul         IT  Inactive         Low
3   Neha    Finance    Active        High
4   Riya         HR  Inactive      Medium
5  Karan         IT    Active        High

In [25]:
df["Department"].cat.categories

Index(['Finance', 'HR', 'IT'], dtype='object')

In [26]:
df["Status"]=df["Status"].astype("category")

In [28]:
df["Performance"]=pd.Categorical(
    df["Performance"],
    categories=["Low","Medium","High"],
    ordered=True
)
print(df)

    Name Department    Status Performance
0   Amit         IT    Active        High
1  Priya         HR    Active      Medium
2  Rahul         IT  Inactive         Low
3   Neha    Finance    Active        High
4   Riya         HR  Inactive      Medium
5  Karan         IT    Active        High

In [29]:
df=df.sort_values("Performance")
print(df)

    Name Department    Status Performance
2  Rahul         IT  Inactive         Low
1  Priya         HR    Active      Medium
4   Riya         HR  Inactive      Medium
0   Amit         IT    Active        High
3   Neha    Finance    Active        High
5  Karan         IT    Active        High

MultiIndex
----------
 A normal DataFrame has one index:
 A Multilndex has multiple levels of index.

In [36]:
import pandas as pd

df=pd.DataFrame({
    "Department":["IT","IT","HR","HR"],
    "YEAR":[2024,2025,2024,2025],
    "Salary":[50000,60000,45000,55000]
})
df=df.set_index(["Department","YEAR"])
print(df)

                 Salary
Department YEAR
IT         2024   50000
           2025   60000
HR         2024   45000
           2025   55000

Selecting data
--------------

In [32]:
df.loc["IT"]

      Salary
YEAR
2024   50000
2025   60000

In [33]:
df.loc[("IT",2024)]

Salary    50000
Name: (IT, 2024), dtype: int64

In [37]:
df=df.reset_index()
print(df)

  Department  YEAR  Salary
0         IT  2024   50000
1         IT  2025   60000
2         HR  2024   45000
3         HR  2025   55000

set_index() → columns become index

reset_index() → index becomes columns

MultiIndex from groupby()
-------------------------

In [39]:
result=df.groupby(["Department","YEAR"])["Salary"].mean()
print(df)

  Department  YEAR  Salary
0         IT  2024   50000
1         IT  2025   60000
2         HR  2024   45000
3         HR  2025   55000

Practice
--------

In [40]:
df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Finance", "Finance"],
    "Year": [2024, 2025, 2024, 2025, 2024, 2025],
    "Salary": [50000, 60000, 45000, 55000, 40000, 48000]
})

In [41]:
df=df.set_index(["Department","Year"])
print(df)

                 Salary
Department Year
IT         2024   50000
           2025   60000
HR         2024   45000
           2025   55000
Finance    2024   40000
           2025   48000

In [42]:
df.loc["IT"]

      Salary
Year
2024   50000
2025   60000

In [43]:
df.loc[("IT",2025)]

Salary    60000
Name: (IT, 2025), dtype: int64

In [44]:
df=df.reset_index()
print(df)

  Department  Year  Salary
0         IT  2024   50000
1         IT  2025   60000
2         HR  2024   45000
3         HR  2025   55000
4    Finance  2024   40000
5    Finance  2025   48000

In [45]:
result=df.groupby(["Department","Year"])["Salary"].mean()
print(result)

Department  Year
Finance     2024    40000.0
            2025    48000.0
HR          2024    45000.0
            2025    55000.0
IT          2024    50000.0
            2025    60000.0
Name: Salary, dtype: float64